apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app-frontend-deployment-mysql
  labels:
    app: two-tier-app-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app-mysql
  template:
    metadata:
      labels:
        app: two-tier-app-mysql
    spec:
      containers:
        - name: two-tier-app-mysql-ctr
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MYSQL_DATABASE
              value: "mydb"
            - name: MYSQL_USER 
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "admin"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysqldata
              mountPath: /var/lib/mysql
      volumes:
       - name: mysqldata
         persistentVolumeClaim:
           claimName: mysql-pvc
