apiVersion: v1
kind: Service
metadata:
  name: two-tier-app-frontend-service
spec:
  selector:
      app: two-tier-app-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
  type: NodePort
